repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: "PRETTIER - Code Formatter"

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: "BLACK Code Formatter"
        language_version: python3.7

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: "0.0.2"
    hooks:
      - id: stylelint
        name: "STYLELINT - CSS linter"
        additional_dependencies:
          ["stylelint@15.3.0", "stylelint-config-standard@20.0.0"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
      - id: check-json
        name: "PRE-COMMIT-HOOKS"

  - repo: https://github.com/pycqa/flake8
    # flake8 config is in setup.cfg
    rev: 5.0.4
    hooks:
      - id: flake8
        name: "FLAKE8 - Style Guide Enforcement"
        language_version: python3.7
        additional_dependencies:
          [
            "flake8-bugbear==22.10.27",
            "flake8-builtins==2.0.1",
            "flake8-print",
            "flake8-comprehensions",
            "flake8-black",
            "flake8-warnings",
            "flake8-django",
          ]
